language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

branches:
  only:
    - master
    - travis

script:
  - javac -version
  - ./install.sh
  - jar tf AlienFX.jar
